output "avd_registration_token" {
  description = "The registration token generated by the Virtual Desktop Host Pool for registration of session hosts"
  value       = azurerm_virtual_desktop_host_pool_registration_info.registration.token
}

output "avd_pool_name" {
  description = "The name of the host pool"
  value       = azurerm_virtual_desktop_host_pool.pool.name
}

output "avd_pool_id" {
  description = "The name of the host pool"
  value       = azurerm_virtual_desktop_host_pool.pool.id
}